<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.12">
  <POU Name="f_mmToInch" Id="{d43840cb-667c-459a-bf74-8b26ff0757f5}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION f_mmToInch : REAL
VAR_INPUT
	rData : REAL;
END_VAR
VAR
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[f_mmToInch := rData * 0.0393701;]]></ST>
    </Implementation>
    <LineIds Name="f_mmToInch">
      <LineId Id="7" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>